### ISSUE TITLE
Incorrect date with "* * * * *" cron statement

### ISSUE THREAD

**Issue by railsmechanic** [jshmrtn/crontab#15]
I think I've found an issue with `Crontab.get_next_run_date("* * * * *")`.
When I call this function at e.g. 09:42:10 I get `{:ok, ~N[2017-01-18 09:42:00]}`. 
However, I think the result should be `{:ok, ~N[2017-01-18 09:43:00]}`.

The `Crontab.get_previous_run_date("* * * * *")` function works as expected and returns `{:ok, ~N[2017-01-18 09:42:00]}`.

What do you think?

**Comment by maennchen** [comment]
Hmm. I think you're right about that. I'll make a fix for that.

**Comment by maennchen** [comment]
Can you please check if your issue is solved with `v0.8.4`?

**Comment by railsmechanic** [comment]
Awesome!
Many thanks for patching this issue. It works as expected, now.
👍 👍 👍

**Comment by maennchen** [comment]
Great :)
