### ISSUE TITLE
Check v1.0.0

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/crontab#29]
I'd be very happy about input on `v1.0.0`.

**Comment by maennchen** [comment]
Hey @railsmechanic,

Would you like to take a look and give me some feedback?

It'd be much appreciated.

**Comment by railsmechanic** [comment]
I'll have a look tomorrow...
Many thanks for that update. 👍

**Comment by maennchen** [comment]
Thank you very much @railsmechanic

**Comment by railsmechanic** [comment]
You're welcome. Good to see someone in europe is using Elixir, too. 😄

**Comment by maennchen** [comment]
I'm relatively new to elixir, but I like it very much. (This library is my first work in elixir ever...)
