### ISSUE TITLE
Extended mode crontabs fail to find valid dates

### ISSUE THREAD

**Issue by mtrudel** [jshmrtn/crontab#48]
To have a task run at 20:16(:40) every evening: 

```
time = ~N[2018-02-26 20:07:00]

# A basic non-extended call works as you would expect
~e[16 20 * * * *] |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
# +> [~N[2018-02-26 20:16:00], ~N[2018-02-27 20:16:00], ~N[2018-02-28 20:16:00]]

# However an extended call does not
~e[40 16 20 * * * *]e |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
# => [~N[2018-02-26 20:16:40]]
```

Perhaps my mental model of this is incorrect, but shouldn't the second call return an enum that includes dates beyond the next invocation? (ie: `[~N[2018-02-26 20:16:40], ~N[2018-02-27 20:16:40], ~N[2018-02-28 20:16:40]]`)?

If this isn't intended behaviour I'm happy to work up a PR to fix, but I want to make sure I'm understanding the intended use case properly.

**Comment by maennchen** [comment]
@mtrudel This seems to be a bug. I'd be happy to accept a PR!

**Comment by mtrudel** [comment]
So we're in agreement, you'd see intended behaviour as being `[~N[2018-02-26 20:16:40], ~N[2018-02-27 20:16:40], ~N[2018-02-28 20:16:40]]` in that case?

**Comment by maennchen** [comment]
@mtrudel Yes, that should be correct.

**Comment by mtrudel** [comment]
Trying to characterize the bug, and noticed something most curious:

```
 time = ~N[2018-02-26 20:07:00]
~N[2018-02-26 20:07:00]
iex(19)> ~e[21 16 21 * * * *]e |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
[~N[2018-02-26 21:16:21], ~N[2018-02-27 21:16:21], ~N[2018-02-28 21:16:21]]
iex(20)> ~e[22 16 21 * * * *]e |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
[~N[2018-02-26 21:16:22]]
iex(34)> ~e[22 15 21 * * * *]e |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
[~N[2018-02-26 21:15:22], ~N[2018-02-27 21:15:22], ~N[2018-02-28 21:15:22]]
iex(35)> ~e[23 15 21 * * * *]e |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
[~N[2018-02-26 21:15:23]]
iex(36)> ~e[23 14 21 * * * *]e |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
[~N[2018-02-26 21:14:23], ~N[2018-02-27 21:14:23], ~N[2018-02-28 21:14:23]]
iex(37)> ~e[24 14 21 * * * *]e |> Crontab.Scheduler.get_next_run_dates(time) |> Enum.take(3)
[~N[2018-02-26 21:14:24]]
```

There's a varying number of seconds into the start of the minute that work as expected, which seem to vary depending on the minute. The number of seconds after the minute which works doesn't seem to vary based on the hour or larger units in the cron expression, nor does it seem to matter what the value of `time` is.

**Comment by mtrudel** [comment]
I haven't started digging into this (hopefully later today), but that looks as good of a place to start as any. Will keep you posted.

**Comment by maennchen** [comment]
@mtrudel I could verify that this is a performance / max cycles problem. The scheduler tries 10'000 times to find a date and will then stop. The date in your example is not found in that amount of cycles.

I did not yet check if it searches for the date less efficiently than other dates. So it's either a performance improvement or bug hunt.

The current algorithm entirely depends on stupid trying until the check passes. Maybe we could somehow make guesses to find the next date more efficiently.

**Comment by maennchen** [comment]
@mtrudel This test passes with `100_000` maximum cycles:

```elixir
test "max runs" do
  time = ~N[2018-02-26 20:07:00]

  run_times = ~e[22 16 21 * * * *]e
  |> Crontab.Scheduler.get_next_run_dates(time)
  |> Enum.take(3)

  assert run_times == [~N[2018-02-26 21:16:22], ~N[2018-02-27 21:16:22], ~N[2018-02-28 21:16:22]]
end
```

**Comment by maennchen** [comment]
@mtrudel If we let all the tests from `Crontab.FunctionalTest` run in extended mode with second 0, there's 26 failures. How could I not see that :S

**Comment by maennchen** [comment]
@mtrudel The python `croniter` package seems to make more intelligent guesses than this library does. See https://github.com/taichino/croniter/blob/master/src/croniter/croniter.py

**Comment by mtrudel** [comment]
Leaving myself a breadcrumb that the implementation in https://github.com/siebertm/parse-cron/pull/34 ought to work here

**Comment by mtrudel** [comment]
Is this issue still open in light of #50?

**Comment by maennchen** [comment]
@mtrudel I’m currently improving the test suite to make sure that it is fully functional
now. I’ll close the issue with the new test cases.
