### ISSUE TITLE
Allow Ecto or Ecto_SQL Version 3

### ISSUE THREAD

**Issue by CaldwellYSR** [jshmrtn/crontab#53]
I am unable to upgrade to the latest version of Ecto because `crontab (version 1.1.4) requires ~> 1.0 or ~> 2.0 or ~> 2.1 * `

From what I can tell y'all are only using Ecto for your Ecto.Type implementation and that doesn't appear to have changed in Ecto 3.0.

**Comment by maennchen** [comment]
Fixed by #52 & released as `v1.1.5`.
