### ISSUE TITLE
crontab struct cannot be saved a map

### ISSUE THREAD

**Issue by jasonandrewduncan** [jshmrtn/crontab#56]
We're using the ecto_type provided with crontab and trying to store a schedule with a range into the DB. It's not encoding properly as JSON and I was looking for ideas and/or enhancements that could be made to make this work. 

I cannot get this part of the struct to JSON encode {:-, 1, 5} (representing a range in CRON, in this case days 1-5). Here's an example of the error I'm getting from Poison.encode! but it seems likely other JSON parsers registered with ecto or even using the native column types of Postres (JSONB) would have similar issues.

If I'm missing something simple please let me know.
From IEX.. with a Json parser loaded.
x = {:-, 1, 5}  
Poison.encode! x

** (Poison.EncodeError) unable to encode value: {:-, 1, 5}
    (poison) lib/poison/encoder.ex:383: Poison.Encoder.Any.encode/2
    (poison) lib/poison.ex:41: Poison.encode!/2

If you alternatively feel it's an issue with the parser then let me know some details as to why and I can create an issue on the Poison library's github.

**Comment by maennchen** [comment]
Hm... This doesn‘t sound like the ecto type is used properly. The ecto type converts the struct into a string. If that‘s not happening, something is wrong.

Can you please share the code of the ecto model?

**Comment by jasonandrewduncan** [comment]
So, this was my mistake I was helping someone else out and I thought that they had it modeled in Ecto when they told me about the error via Instant Message and asked for my help. They in fact just we're messing around in iex trying to json encode the struct directly, the ecto_type worked fine when they put it into their model.. so sorry about the false alarm.
